### ISSUE TITLE
Tests - test/test_stdlib.rb

### ISSUE THREAD

**Issue by MSP-Greg** [larskanis/rubyinstaller2#12]
Re d21930d37dfdc757f56e8402ba58d833e106d80b, I think there are a few std-lib 'libraries' that load 'extension'/c code.  For instance, CGI, JSON and racc/cparse.

Would you accept a PR like [test_std_lib.rb](https://gist.github.com/MSP-Greg/877b8ceaac02f8e44df8a2398757b2c1)?

A little easier to keep track of...

**Comment by larskanis** [comment]
Yes, looks good. The aim of the test is to check that all libraries and
depending dlls are in place and can be loaded. I wasn't really finished
yet, but it turned out, that checking the main constant is enough.

**Comment by MSP-Greg** [comment]
FYI, it isn't apparent from the constants shown in the PR, but CGI & JSON do load everything on the main 'require'.  For instance, the `CGI::Escape` class is loaded whenever one does a `require "CGI"`.

I got rather familiar with the layout of Ruby Std-lib when I put together the the code to document it...

**Comment by larskanis** [comment]
Solved per #13
