### ISSUE TITLE
Rubyinstaller2 version

### ISSUE THREAD

**Issue by fuzzybear3965** [larskanis/rubyinstaller2#16]
I recently installed one of the rubyinstaller2 releases and I don't know how to determine if it was 2.4.0-6 or 2.4.0-7. Is this information embedded into the installation? I could not find it.

If this information isn't included in the installation I would recommend that the installer place a RELEASE (or similar) file in the root of the installation directory. This file could include a link to the GitHub repository for this project and the commit associated with the build (in case someone doesn't install a pre-compiled release available on this GitHub repository).

**Comment by fuzzybear3965** [comment]
That's awesome, thanks. I didn't know that I could `ridk version` to get the release information. Is `ridk` short for Rubyinstaller(2) development kit?

**Comment by larskanis** [comment]
`ri` is already taken, `ruin` didn't seem to be a good name and so it's something like "ruby installer and it's development kit"...

Did `ridk version` work for you?

**Comment by fuzzybear3965** [comment]
Yeah, `ridk version` solved the main focus of this issue. But, people may not install one of the releases, so having the commit information reported by `ridk version` is good, too. I think that's what changed with your recent commit. So, I'm happy.
