### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by fuzzybear3965** [larskanis/rubyinstaller2#17]
I see license files for the gems, rake, and gem itself. But, I don't see a license file for the Ruby language/execution environment. Is this somewhere where I'm not seeing it?

I'm on Windows 10 if that affects the response (path description).

**Comment by larskanis** [comment]
I usually don't care much about licenses. It should simply stay not in the
way to do anything useful with the piece of software.

There is a license file in root directory of the repository and the license
is acknowledged when running the installer. Where do you expect another
license information?

**Comment by fuzzybear3965** [comment]
I had expected one in the root of the installation directory. But, for all I know just including it in the installer and/or the source repo is fine.

**Comment by fuzzybear3965** [comment]
Great!
