### ISSUE TITLE
MSYS2 installed using Chocolatey is neither detected or usable

### ISSUE THREAD

**Issue by luislavena** [larskanis/rubyinstaller2#23]
## What problems are you experiencing?

On chocolatey-managed environments, the default installation of MSYS2 package gets instaled in a differen directory and doesn't add details into the registry, thus not being detected by RubyInstaller.

By default Chocolatey installs it into `C:\tools\msys64`, which differs from the default directory that RubyInstaller might be looking for.

## Steps to reproduce

- Uninstall any MSYS2 installation done with `ridk`
- Using Admin PowerShell, install MSYS2 using Chocolatey `choco install -y msys2`
- Using `msystem msys`, install toolchain as indicated in the README: `pacman -S base-devel mingw-w64-x86_64-toolchain`
- Check output of `ridk version`, there is no mention of cc or sh.
- Only when using `msystem mingw64`, GCC information is displayed in `ridk version`
- Attempt to install a gem fails with same *MSYS2 could not be found*

```
C:\Users\Luis>gcc --version
'gcc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Luis>msystem mingw64

<MINGW64> C:\Users\Luis>gcc --version
gcc (Rev2, Built by MSYS2 project) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

<MINGW64> C:\Users\Luis>ridk version
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.0
  platform: x64-mingw32
ruby_installer:
  version: 2.4.0-8
  git_commit: c55856f
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 6.3.0

<MINGW64> C:\Users\Luis>gem install oj --platform=ruby
Fetching: oj-2.18.1.gem (100%)
MSYS2 could not be found.
Please download and install MSYS2 from https://msys2.github.io/
```

## What's the output from `ridk version`?

```yaml
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.0
  platform: x64-mingw32
ruby_installer:
  version: 2.4.0-8
  git_commit: c55856f
```

---

If this is too complicated to resolve, perhaps it will be required to add a caveat into the documentation about it.

Thank you. ❤️ ❤️ ❤️

**Comment by MSP-Greg** [comment]
@luislavena

Although not the same, but somewhat related. I've got my msys2 install on D:  I created a symlink to it in C:, and everything works fine.

Is that a reasonable thing to ask a user to create? If so, a note in the README.

**Comment by luislavena** [comment]
@MSP-Greg if MSYS2 was installed using the installer, it will record information into the registry, which is what RubyInstaller is trying to figure it out when `C:/msys32` or `C:/msys64` is not found:

https://github.com/larskanis/rubyinstaller2/blob/master/lib/ruby_installer/msys2_installation.rb#L22-L43

**Comment by MSP-Greg** [comment]
@luislavena I think the early versions of RI2 had a problem finding it in the registry, so I added the symlink back then.  When I get a chance to test, I'll remove it and see if RI2 finds MSYS2.

**Comment by larskanis** [comment]
Chocolatey sets the PATH variable to the msys2 root folder. I think it's suitable to iterate over the PATH folders to find the msys2 installation.
