### ISSUE TITLE
Silent installation support

### ISSUE THREAD

**Issue by FeodorFitsner** [larskanis/rubyinstaller2#24]
Hi guys,

Thank you for marking the new Ruby installer for Windows!

I've noticed the installer is based on InnoSetup, so assume silent (unattended) installation mode is supported, but still I'd like to clarify what would be exact command to install Ruby 2.4 *without* dependencies such as MSYS.

Thank you!

**Comment by larskanis** [comment]
I just added the answer to the FAQ: https://github.com/larskanis/rubyinstaller2/wiki/FAQ

**Comment by FeodorFitsner** [comment]
Fantastic, thank you!
