### ISSUE TITLE
News: Ruby 2.4.1 Release!

### ISSUE THREAD

**Issue by duytrung** [larskanis/rubyinstaller2#26]
Just a news from rubylang website: The release of 2.4.1 is available.

Regards ;-)

**Comment by larskanis** [comment]
Ruby is already updated per commit https://github.com/larskanis/rubyinstaller2/commit/606d5849ccbf9331dd4deeaf78c47c392694a40c on the gem branch. The gem branch will probably merged soon to master.

**Comment by larskanis** [comment]
The ruby version 2.4.1 is on the master branch and I will publish a new pre-release.
